### ISSUE TITLE
autocompletion does not work on RobotFrameWork keywords with PyCharm 2019.2 and Eclipse  version 2019-03(4.11.0)

### ISSUE THREAD

**Issue by remicharleslageixarena** [robotframework/robotframework#3285]
My configuration:
OS : **ubuntu 18.04**
**Pycharm : community 2019.02  used plugings: intellibot,, intellibot@seleniumLibrary Patched**

configuration robotframework:
**robotframework (3.1.2)**
robotframework-appiumlibrary (1.5.0.4)
robotframework-databaselibrary (1.2.4)
robotframework-jenkins (1.0.2)
robotframework-requests (0.5.0)
robotframework-selenium2library (3.0.0)
**robotframework-seleniumlibrary (3.3.1**)

**the autocompletion does not work on robotFrameWork keywords on Pycharm.
I have the same issue  with Eclipse Eclipse :  version 2019-03(4.11.0)**
Please could you help me to fix this issue?
thanks in advance

**Comment by pekkaklarck** [comment]
This is most likely due to the plugin not recognizing the dynamic API that SeleniumLibrary nowadays uses. I've heard there is a plugin that has this issue fixed by hard-coding SeleniumLibrary keywords. That's not a very good solution, but ought to provide a workaround until someone creates a plugin that can actually use the dynamic API. Anyway, this issue tracker is for issues related to Robot Framework itself. Issues related to plugins should be reported to their own trackers. Mailing lists, Slack, etc. can also be used to ask others how they've resolved this issue.

**Comment by kilicemre** [comment]
@pekkaklarck  @remicharleslageixarena  Were any of you able to resolve this issue? I am still facing with the similar issue while using on Appium library.

**Comment by pekkaklarck** [comment]
The Language Server Protocol based plugin supports all Robot's library APIs by using Robot's APIs directly. I recommend giving it a try.
