### ISSUE TITLE
AttributeError: 'objc.function' object has no attribute '__annotations__'

### ISSUE THREAD

**Issue by eesss34690** [robotframework/robotframework#4059]
I was building the Regression test and confronted with error like below
`
[ ERROR ] Unexpected error: AttributeError: 'objc.function' object has no attribute '__annotations__'
Traceback (most recent call last):
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/utils/application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/run.py", line 450, in main
    result = suite.run(settings)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/model.py", line 296, in run
    self.visit(runner)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/model/visitor.py", line 85, in visit_suite
    if self.start_suite(suite) is not False:
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/suiterunner.py", line 72, in start_suite
    ns.handle_imports()
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/namespace.py", line 55, in handle_imports
    self._handle_imports(self._imports)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/namespace.py", line 66, in _handle_imports
    self._import(item)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/namespace.py", line 74, in _import
    action(import_setting)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/namespace.py", line 127, in _import_library
    lib = IMPORTER.import_library(name, import_setting.args,
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/importer.py", line 48, in import_library
    lib = self._import_library(name, positional, named, lib)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/importer.py", line 78, in _import_library
    lib.create_handlers()
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/testlibraries.py", line 119, in create_handlers
    self._create_handlers(self.get_instance())
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/testlibraries.py", line 241, in _create_handlers
    handler, embedded = self._try_to_create_handler(name, method)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/testlibraries.py", line 299, in _try_to_create_handler
    handler = self._create_handler(name, method)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/testlibraries.py", line 310, in _create_handler
    return Handler(self, handler_name, handler_method)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/handlers.py", line 40, in Handler
    return _PythonHandler(library, name, method)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/handlers.py", line 143, in __init__
    _RunnableHandler.__init__(self, library, handler_name, handler_method,
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/handlers.py", line 60, in __init__
    self.arguments = self._parse_arguments(handler_method)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/handlers.py", line 147, in _parse_arguments
    return PythonArgumentParser().parse(handler_method, self.longname)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/arguments/py3argumentparser.py", line 30, in parse
    self._set_types(spec, handler)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/arguments/py3argumentparser.py", line 65, in _set_types
    spec.types = self._get_type_hints(handler, spec)
  File "/Users/pqa/.pyenv/versions/3.9.5/lib/python3.9/site-packages/robot/running/arguments/py3argumentparser.py", line 71, in _get_type_hints
    return handler.__annotations__
`
Which seems to be stem from the failure when trying to get the type_hint in _py3argumentparser_

```
def _get_type_hints(self, handler, spec):
        try:
            type_hints = typing.get_type_hints(handler)
        except Exception:  # Can raise pretty much anything
            return handler.__annotations__
```

Any suggestion for the fix? Thanks.

My environment setting:
Environment: MacOS BigSur Version 11.4
On Apple Mac mini M1
Python: 3.9.5 under Rosetta 2

**Comment by pekkaklarck** [comment]
Can you share example code causing this issue? It's probably enough to change `return handler.__annotations__` to `return getattr(handler, '__annotations__', {})` but it would be good to add tests for it as well.

**Comment by eesss34690** [comment]
The problem is fixed with this change. And the warning showing up is like this.
```
.pyenv/versions/3.9.5/lib/python3.9/site-packages/rubicon/objc/ctypes_patch.py:21: UserWarning: rubicon.objc.ctypes_patch has only been tested with Python 3.4 through 3.8. You are using Python 3.9.5. Most likely things will work properly, but you may experience crashes if Python's internals have changed significantly.
```
I think it is because I import the python function files which use **ctypes** and the warning cannot show up.

**Comment by pekkaklarck** [comment]
So the fix I proposed worked? That's good to know. Could you still show the library code that caused the problem? It would help creating a test for this issue.

The warning about rubicon most likely isn't related to this problem.

**Comment by eesss34690** [comment]
The library which cause the error is Quartz. I used the following library in part of the code and causes the error.
And yes, the warning is not related to the error since it still came up after I removed Quartz.
```
from Quartz import CGWindowListCopyWindowInfo, kCGNullWindowID, kCGWindowListOptionAll
```

**Comment by pekkaklarck** [comment]
Was that import alone enough to cause the error or did you use the imported items somewhere?

**Comment by pekkaklarck** [comment]
I tried to create a function without `__annotations__` on Python but that doesn't seem to be possible. Most likely this problem can only occur with C based functions. Anyway, I changed the code to use `getattr()` which reportedly fixed the problem.
